M48
; DRILL file {KiCad (6.0.11)} date Wed Jan 24 22:10:23 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-24T22:10:23+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X152.19Y-47.305
X163.62Y-47.305
X168.37Y-47.305
X179.8Y-47.305
T2
X154.73Y-66.36
X177.26Y-66.36
T0
M30
